version: '3'

services:
    mongodb:
        image: mongo:latest
        networks:
            - bridge-network_TP6
        volumes:
            - mongodb-volume:/data/db

    web:
        build: .
        container_name: appFlaskPython
        ports:
            -  "5000:5000"
        networks:
            - bridge-network_TP6
        volumes:
            - ./toBeRead.txt:/app/toBeRead.txt

networks:
    bridge-network_TP6:

volumes:
    mongodb-volume: